### PR TITLE
README for GCHMC

### PR DESCRIPTION
**Pull request by spirilaurentiu**

### CODE REVIEW

**Comment by daveminh** [comment]
So are internal coordinates completely flexible? Are rings and rigid bodies inflexible?

**Comment by daveminh** [comment]
Can you have multiple molecules in the mol2? e.g. dock6 output?

**Comment by spirilaurentiu** [comment]
Internal coordinates are completely flexible. Rings are completely flexible. Rigid bodies are completely inflexible.
From the mol2 file only the first molecule will be read. The rest is ignored.

**Comment by spirilaurentiu** [comment]
I saw a problem in the MoleculeReader. I am fixing it now.

**Pull request merged**
